apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    helm.sh/chart: kube-prometheus-6.1.4
  name: prometheus-kube-prometheus-prometheus
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9090
  selector:
    app: prometheus
    prometheus: prometheus-kube-prometheus-prometheus
  type: LoadBalancer
