apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: thanos
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-5.3.1
  name: thanos-query
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  type: LoadBalancer
